### PR TITLE
fix: #3043,#3044, #3048 Refactor several UI components and improve er…

### LINKED ISSUE #3043: Organization's link is doubled and overlapped with different font sizes
**Description**:
Adding a link to an organization results in a doubled text in the URI form

**Steps**:
1. Access the Organizations page
2. Access an organization
3. Add a URI
4. Go back to the Organizations page
5. Access the test organization

**Expected behavior**:
The URI should be correctly displayed

**Actual behavior**:
The URI is doubled with two different font sizes

**Screenshots**:
Screenshot 2023-08-04 at 15 02 30

### LINKED ISSUE #3044: Social link can not be accessed after editing
**Describe the bug**
After editing the Social link, it can only be accessed after a workaround

**How to reproduce**
1. Go to Organizations Page
2. Edit the Social link
3. Click out
4. Click the "go-to" icon for the link

**Expected behavior**
The go-to icon should appear at the end of the Social Link and it should be clickable

**Actual behavior**
The go-to icon disappears when the cursor reaches the Social Link

**Obs.**
Clicking inside the Social Link and clicking out again, will fix the behavior

**Clip**
https://github.com/openline-ai/openline-customer-os/assets/125381623/2f3e559f-2de6-4e2c-ba2a-ae7a6916f753

### LINKED ISSUE #3048: Ui fixes
- About
- Once I click on a link to edit and click away again, the link icons goes a bit wonky. One of them will show up the whole time and disappear on hover.
- This jumbled up link issue popped up again on the website link
- Can you update the styling of this button type to reflect the designs [updated globally so all buttons in that theme will reflect that]
- Can we center align this component? It’s currently sitting a bit lower on the line.
- Can you change the copy for the above snackbar to: “ Link copied”
- This snackbar should be green and not red. Can you check if an error shows the correct colour? The styling is also different from the design reference.
- TO, CC, BCC should not be spaced out equally (reference design)
- The email tab is a bit off. It sits a bit higher over the Now line.

Thank you for your bug report!  We ❤️ squashing 🪲

### PR DESCRIPTION
**Pull request by Kasia9090**
…ror handling

This commit includes several updates to improve user experience and enhance error handling. The toast.error method is replaced with toast.success in toastSuccess.tsx for success messages. The email composing component has been improved to handle potential errors correctly by using toastError.

Additions have been made to the getTimeline graphql query to fetch 'summary' and 'actionItems' fields which appears to be necessary for subsequent use.

Certain UI elements like SocialInput and UrlInput have been refactored for better hover functionality. The BCC option in ParticipantsSelectGroup component is commented out for undisclosed reasons and might be related to bug #3044.

Styling updates have been made in several places for a uniform and improved look and feel. For instance, box-shadow is being used instead of drop-shadow for better browser compatibility.

Also, to allow the user more time to read the toast messages, the autoClose time has been significantly increased in layout.tsx.

Lastly, debugging logs are added in the OrganizationTimeline.tsx file, presumably useful for the ongoing testing and debugging phase.

## Changes

What types of changes does your code introduce?  _Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe below)

### CODE REVIEW

File: packages/apps/spaces/app/layout.tsx [hunk 1]
```diff
@@ -49,7 +49,7 @@ export default async function RootLayout({
               {children}
               <ToastContainer
                 position='bottom-right'
-                autoClose={3000}
+                autoClose={3000000}
```
Comment (steynviljoen67) [inline packages/apps/spaces/app/layout.tsx]: For the toast I would recommend a time of 8 seconds.

Comment (Kasia9090) [reply packages/apps/spaces/app/layout.tsx]: done

**Review by edifirut — APPROVED** [review]
