### PR TITLE
fix: #2357, #2358, #2359 Bug fixes, external links, table skeleton, edit mode

### LINKED ISSUE #2357: [spaces] Edit mode persists between pages
**Describe the bug**
Edit mode persists between pages

**How to reproduce**
1. Go to 'details page
2. Click on edit button
3. Go back to table and select other contact / org
4. See edit mode is enabled

**Expected behavior**
Edit mode does not persist between pages

Thank you for your bug report!  We ❤️ squashing 🪲

### LINKED ISSUE #2358: [spaces] Organization domain link leads to details page
**How to reproduce**
1. Go to organizations table
2. Click on domain link
3. See that details page opened
4. same behaviour is present on details page domain link

**Expected behavior**
Domain link leads to organization website

Thank you for your bug report!  We ❤️ squashing 🪲

### LINKED ISSUE #2359: [spaces] Table skeleton ui does not match table structure
**Describe the bug**

**How to reproduce**
1. Go to contacts table view
2. see skeleton
3. see loaded table

**Expected behavior**
Skeleton match loading component structure

Thank you for your bug report!  We ❤️ squashing 🪲

### PR DESCRIPTION
**Pull request by Kasia9090**
## Proposed changes

-  #2359
- #2358
- #2357

What types of changes does your code introduce?  _Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe below)

### CODE REVIEW

File: packages/apps/spaces/components/organization/organization-list/columns/OrganizationListColumns.tsx [hunk 1]
```diff
@@ -88,13 +88,8 @@ export const organizationListColumns: Array<Column<Organization>> = [
...
 
     template: (organization) => {
-      return (
-        <LinkCell
-          label={organization.domain}
-          subLabel={organization.website}
-          url={`/organization/${organization.id}`}
-        />
-      );
+      if (!organization.website) return <div />;
```
Comment (acalinica) [inline packages/apps/spaces/components/organization/organization-list/columns/OrganizationListColumns.tsx:91]: Does it work to return `null` instead of an empty `div`?

**Review by acalinica — APPROVED** [review]

**Review by edifirut — APPROVED** [review]

**Review by edifirut — APPROVED** [review]
