### PR TITLE
fix: #2350 mutations issues on editable fields

### LINKED ISSUE #2350: [Spaces] - Contact Page mutation issues
Describe the bug
There are several errors and inconsistencies while performing updates/mutations on editable records on a given Contact Page.

Thank you for your bug report!  We ❤️ squashing 🪲

### PR DESCRIPTION
**Pull request by acalinica**
## Proposed changes

fixes #2350 

## Changes

What types of changes does your code introduce?  _Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe below)

### CODE REVIEW

File: packages/apps/spaces/hooks/useContact/useAddContactTag.ts [hunk 1]
```diff
@@ -18,8 +18,7 @@ export const useAddTagToContact = ({
   contactId: string;
 }): Result => {
   const client = useApolloClient();
-  const [addTagToContactMutation, { loading, error, data }] =
-    useAddTagToContactMutation();
+  const [addTagToContactMutation] = useAddTagToContactMutation();
```
Comment (Kasia9090) [inline packages/apps/spaces/hooks/useContact/useAddContactTag.ts:15]: (optional) This could be opportunity to drop try catch approach from here and use `onError`, `onCompleted` and `update` methods from apollo

**Review by Kasia9090 — DISMISSED** [review]
Optional refactor requested in the comment, otherwise good to go 💪

**Review by Kasia9090 — APPROVED** [review]
