### PR TITLE
[COS] - Remove tenant organization from finder

### LINKED ISSUE #1150: Remove tenant org from Everything list
**Describe the bug**
Currently tenant org appears in Everything list - this should be a special case and removed from 'Everything'

Thank you for your bug report!  We ❤️ squashing 🪲

### PR DESCRIPTION
**Pull request by edifirut**

### CODE REVIEW

File: packages/server/customer-os-api/repository/query_repository.go [hunk 1]
```diff
@@ -91,7 +91,7 @@ func (r *queryRepository) GetOrganizationsAndContacts(ctx context.Context, sessi
           MATCH (t:Tenant {name:$tenant})--(o:Organization)
 		  MATCH (t)--(c:Contact)
 		  MATCH (o)-[rel]-(c)
-		  WHERE (%s) OR (%s)
+		  WHERE o.tenantOrganization = false AND ((%s) OR (%s))
```
Comment (alexopenline) [inline packages/server/customer-os-api/repository/query_repository.go]: update here

**Review by alexopenline — APPROVED** [review]

**Review by alexopenline — APPROVED** [review]
