### PR TITLE
redis connection fix

### LINKED ISSUE #2692: comms - redis connections not working
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

Thank you for your bug report!  We ❤️ squashing 🪲

### PR DESCRIPTION
**Pull request by gabriel0003**
## Changes

What types of changes does your code introduce?  _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe below)

### CODE REVIEW

File: packages/server/comms-api/main.go [hunk 1]
```diff
@@ -2,22 +2,21 @@ package main
...
-	"github.com/redis/go-redis/v9"
 	"log"
 )
 
 func main() {
 	config := loadConfiguration()
 
 	graphqlClient := graphql.NewClient(config.Service.CustomerOsAPI)
-	redisUrl := fmt.Sprintf("redis://%s", config.Redis.Host)
+	redisUrl := fmt.Sprintf("rediss://%s", config.Redis.Host)
```
Comment (edifirut) [inline packages/server/comms-api/main.go:20]: the s is doubled in rediss

**Review by edifirut — CHANGES_REQUESTED** [review]

**Review by edifirut — APPROVED** [review]
